version: "3"

# See https://concourse-ci.org/docker-compose.yml for a default template
services:
  concourse:
    image: concourse/concourse:7.7.1
    command: "quickstart"
    ports:
      - "8080:8080"
    privileged: true
    depends_on: [db]
    environment:
      - CONCOURSE_POSTGRES_HOST=db
      - CONCOURSE_POSTGRES_USER=concourse
      - CONCOURSE_POSTGRES_PASSWORD=password
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL=http://localhost:8080
      - CONCOURSE_ADD_LOCAL_USER=user:password
      - CONCOURSE_MAIN_TEAM_LOCAL_USER=user
      - CONCOURSE_WORKER_CONTAINERD_DNS_SERVER=8.8.8.8
      - CONCOURSE_WORKER_RUNTIME=containerd
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=concourse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=concourse
